Baris/refactor beans
hydrabeer/doorkey pull request #35
Opened 2024-11-21 21:07 UTC by bbayazit16

Refactored to simplify property listener logic.

2024-11-21 22:03 UTC, HACKERALERT approved these changes

2024-11-22 20:08 UTC, 9naama requested changes
Check style error fixes left in comments, please address otherwise LGTM

2024-11-22 20:08 UTC, 9naama commented on src/main/java/views/TestView.java
>  import javax.swing.*;
Fix * input check style error

2024-11-22 20:08 UTC, 9naama commented on src/main/java/views/TestView.java
> +import java.awt.event.ActionEvent;
adjust order as necessary to satisfy check style

2024-11-22 20:08 UTC, 9naama commented on src/main/java/views/TestViewModel.java
> +public class TestViewModel extends ViewModel<TestViewState> {
fix "type Javadoc comment is missing null tag."

2024-11-22 20:08 UTC, 9naama commented on src/main/java/views/TestViewState.java
> +package views;
file needs to end with new line

2024-11-22 20:08 UTC, 9naama commented on src/main/java/views/TestViewState.java
> +public class TestViewState {
address missing null tag

2024-11-23 21:02 UTC, 9naama approved these changes

2024-11-23 22:32 UTC, merged