Amaan/create password vault item view
hydrabeer/doorkey pull request #49
Opened 2024-11-27 22:54 UTC by 9naama

Password Vault Item view, main view UI work, and some changes to copy credentials.

2024-11-28 04:13 UTC, hydrabeer requested changes
Adherence to CA looks great. Can merge with more tests included

2024-11-28 04:13 UTC, hydrabeer commented on mystyle.xml
Why is this part of the PR?

2024-11-28 23:26 UTC, HACKERALERT commented on src/main/java/service/home/interface_adapter/HomePresenter.java
> +            default -> throw new RuntimeException("Unhandled vault item type: " + item.getType());
I think in the exception folder there is an InvalidVaultItemException that may be more descriptive here

2024-11-28 23:33 UTC, HACKERALERT commented on src/main/java/views/HomeView.java
> +        final JButton accessButton = new DoorkeyButton.DoorkeyButtonBuilder("\uD83D\uDD13")
add a cmoment to descrie what \uD83D\uDD13 is

2024-11-29 00:51 UTC, HACKERALERT approved these changes

2024-11-29 01:33 UTC, saeedshrouf approved these changes
Good job on making requested changes with testing, architecture looks really good also.

2024-11-29 03:22 UTC, hydrabeer approved these changes

2024-11-29 03:22 UTC, merged